#!/usr/bin/env bun
/**
 * Caddyfile Generator
 *
 * Two-file architecture:
 * - services.json: Service structure (port, stripPath) - tracked in git
 * - services-state.json: Operational state (live/maintenance) - server-only
 *
 * Usage:
 *   bun generate.ts                    # Generate and reload
 *   bun generate.ts --dry-run          # Preview without writing
 *   bun generate.ts maint <service>    # Toggle maintenance mode
 *   bun generate.ts add <service> <port>  # Add new service
 *   bun generate.ts remove <service>   # Remove service
 *   bun generate.ts list               # List all services
 */

import { $ } from "bun";

const SCRIPT_DIR = import.meta.dir;
const SERVICES_STRUCTURE_FILE = `${SCRIPT_DIR}/services.json`;
const SERVICES_STATE_FILE = `${SCRIPT_DIR}/services-state.json`;
const CADDYFILE_PATH = "/srv/caddy/config/Caddyfile";
const CADDYFILE_BACKUP = `${CADDYFILE_PATH}.bak`;
const TEMP_FILE = "/tmp/Caddyfile.new";
const CADDY_CONTAINER = "caddy";
const CONTAINER_STAGING = "/tmp/Caddyfile.candidate";
const DOMAIN = "app.swedenindoorgolf.se";
const MAINTENANCE_ROOT = "/maintenance";

// Structure: port, stripPath (tracked in git)
interface ServiceStructure {
  port: number;
  stripPath?: boolean; // default true (handle_path), false = handle (keep path)
  description?: string;
}

// State: live/maintenance (server-only)
interface ServiceState {
  live: boolean;
}

// Combined for Caddyfile generation
interface ServiceConfig extends ServiceStructure {
  live: boolean;
}

type ServicesStructure = Record<string, ServiceStructure>;
type ServicesState = Record<string, ServiceState>;
type Services = Record<string, ServiceConfig>;

async function loadServicesStructure(): Promise<ServicesStructure> {
  const file = Bun.file(SERVICES_STRUCTURE_FILE);
  if (!(await file.exists())) {
    console.error(`❌ ${SERVICES_STRUCTURE_FILE} not found. Create it first.`);
    process.exit(1);
  }
  return file.json();
}

async function loadServicesState(): Promise<ServicesState> {
  const file = Bun.file(SERVICES_STATE_FILE);
  if (!(await file.exists())) {
    // If state file doesn't exist, return empty object (will default to live: true)
    return {};
  }
  return file.json();
}

async function loadServices(): Promise<Services> {
  const structure = await loadServicesStructure();
  const state = await loadServicesState();

  // Merge: structure + state, defaulting to live: true
  const merged: Services = {};
  for (const [name, config] of Object.entries(structure)) {
    merged[name] = {
      ...config,
      live: state[name]?.live ?? true, // Default to live if not in state file
    };
  }

  return merged;
}

async function saveServicesStructure(services: ServicesStructure): Promise<void> {
  const content = JSON.stringify(services, null, 2) + "\n";
  const tempFile = "/tmp/services.json.new";
  await Bun.write(tempFile, content);
  await $`cat ${tempFile} | sudo tee ${SERVICES_STRUCTURE_FILE} > /dev/null`;
  await $`rm ${tempFile}`;
}

async function saveServicesState(state: ServicesState): Promise<void> {
  const content = JSON.stringify(state, null, 2) + "\n";
  const tempFile = "/tmp/services-state.json.new";
  await Bun.write(tempFile, content);
  await $`cat ${tempFile} | sudo tee ${SERVICES_STATE_FILE} > /dev/null`;
  await $`rm ${tempFile}`;
}

function generateServiceBlock(path: string, config: ServiceConfig): string {
  const stripPath = config.stripPath !== false; // default true
  
  if (config.live) {
    if (stripPath) {
      return `    handle_path /${path}/* {
        reverse_proxy localhost:${config.port}
    }`;
    } else {
      return `    handle /${path}* {
        reverse_proxy localhost:${config.port}
    }`;
    }
  } else {
    // Maintenance mode - always use handle (broader match)
    return `    handle /${path}* {
        # live_port:${config.port}
        # strip_path:${stripPath}
        root * ${MAINTENANCE_ROOT}
        rewrite * /index.html
        file_server
    }`;
  }
}

function generateCaddyfile(services: Services): string {
  const serviceBlocks = Object.entries(services)
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([name, config]) => generateServiceBlock(name, config))
    .join("\n\n");

  return `# Auto-generated by generate.ts — DO NOT EDIT MANUALLY
# Source of truth: ${SERVICES_STRUCTURE_FILE}
# Generated: ${new Date().toISOString()}

${DOMAIN} {
    log {
        output file /data/log/access.log {
            roll_size 1gb
            roll_keep 3
            roll_keep_for 720h
        }
    }

    # Serve robots.txt
    handle_path /robots.txt {
        file_server {
            root /srv/sig-web/public
        }
    }

    # Serve sitemap.xml
    handle_path /sitemap.xml {
        file_server {
            root /srv/sig-web/public
        }
    }

${serviceBlocks}

    # Default fallback
    handle {
        respond "Welcome to ${DOMAIN}!"
    }
}
`;
}

// Check the candidate config INSIDE the Caddy container before it replaces the
// live file. Without this a bad generate silently destroys a good Caddyfile:
// `caddy reload` fails so the running process keeps serving the old config and
// nothing looks broken — but the file on disk is now invalid, and the next
// container restart takes every service down at once.
//
// Distinguishes "config is invalid" (abort) from "couldn't run the check"
// (warn and continue — the container being down is not a reason to block a
// regeneration, and the backup/restore below still covers us).
async function validateCaddyfile(content: string): Promise<"valid" | "invalid" | "skipped"> {
  await Bun.write(TEMP_FILE, content);

  try {
    await $`sudo docker cp ${TEMP_FILE} ${CADDY_CONTAINER}:${CONTAINER_STAGING}`.quiet();
  } catch {
    console.warn("⚠️  Could not stage config in the caddy container — skipping validation");
    return "skipped";
  }

  try {
    await $`sudo docker exec ${CADDY_CONTAINER} caddy validate --config ${CONTAINER_STAGING} --adapter caddyfile`.quiet();
    console.log("✅ Caddyfile validated");
    return "valid";
  } catch (error: any) {
    console.error("❌ Generated Caddyfile is INVALID — live config left untouched:\n");
    const detail = (error?.stderr?.toString?.() || error?.stdout?.toString?.() || String(error)).trim();
    console.error(detail);
    return "invalid";
  } finally {
    await $`sudo docker exec ${CADDY_CONTAINER} rm -f ${CONTAINER_STAGING}`.quiet().nothrow();
  }
}

async function writeCaddyfile(content: string, dryRun: boolean): Promise<void> {
  if (dryRun) {
    console.log("📋 [DRY-RUN] Would generate:\n");
    console.log("─".repeat(60));
    console.log(content);
    console.log("─".repeat(60));
    return;
  }

  // Keep the last known-good file so a failed reload can put disk back in sync
  // with what Caddy is actually running. nothrow: absent on the very first run.
  await $`sudo cp -f ${CADDYFILE_PATH} ${CADDYFILE_BACKUP}`.quiet().nothrow();

  // Write to temp file first
  await Bun.write(TEMP_FILE, content);

  // Use cat | tee to preserve inode (required for Docker bind mounts)
  await $`cat ${TEMP_FILE} | sudo tee ${CADDYFILE_PATH} > /dev/null`;
  await $`rm ${TEMP_FILE}`;

  console.log("✅ Caddyfile written");
}

// Reload failed → Caddy is still serving the OLD config, but the file on disk is
// the new one. Put the file back so disk matches the running process; otherwise
// the next restart silently boots a config nobody chose.
async function restoreCaddyfile(): Promise<void> {
  try {
    await $`sudo test -f ${CADDYFILE_BACKUP}`.quiet();
  } catch {
    console.error("⚠️  No backup to restore — Caddyfile on disk is the failed config");
    return;
  }
  try {
    // cat | tee, not mv: the Docker bind mount requires the inode to survive
    await $`sudo cat ${CADDYFILE_BACKUP} | sudo tee ${CADDYFILE_PATH} > /dev/null`;
    console.error("↩️  Restored previous Caddyfile from .bak");
  } catch (error) {
    console.error(`⚠️  Could not restore backup: ${error}`);
  }
}

async function reloadCaddy(dryRun: boolean): Promise<void> {
  if (dryRun) {
    console.log("📋 [DRY-RUN] Would reload Caddy");
    return;
  }

  console.log("🔄 Formatting and reloading Caddy...");

  try {
    await $`sudo docker exec -w /etc/caddy ${CADDY_CONTAINER} caddy fmt --overwrite Caddyfile`.quiet();
    await $`sudo docker exec ${CADDY_CONTAINER} caddy reload --config /etc/caddy/Caddyfile --adapter caddyfile --force`;
    console.log("✅ Caddy reloaded");
  } catch (error) {
    console.error("❌ Caddy reload failed. Check logs with: sudo docker logs caddy --tail 20");
    await restoreCaddyfile();
    throw error;
  }
}

async function listServices(services: Services): Promise<void> {
  console.log("\nCurrent services:");
  console.log("─".repeat(50));
  console.log(`${"SERVICE".padEnd(20)} ${"PORT".padEnd(8)} STATUS`);
  console.log("─".repeat(50));

  for (const [name, config] of Object.entries(services).sort(([a], [b]) => a.localeCompare(b))) {
    const status = config.live ? "🟢 live" : "🚧 maint";
    console.log(`${name.padEnd(20)} ${String(config.port).padEnd(8)} ${status}`);
  }
  console.log("─".repeat(50));
  console.log(`Total: ${Object.keys(services).length} services\n`);
}

async function main(): Promise<void> {
  const args = process.argv.slice(2);
  const dryRun = args.includes("--dry-run");
  const filteredArgs = args.filter((a) => a !== "--dry-run");
  const command = filteredArgs[0];

  const services = await loadServices();

  switch (command) {
    case "list": {
      await listServices(services);
      return;
    }

    case "maint": {
      const serviceName = filteredArgs[1];
      if (!serviceName) {
        console.error("Usage: bun generate.ts maint <service>");
        process.exit(1);
      }
      if (!services[serviceName]) {
        console.error(`❌ Service '${serviceName}' not found`);
        process.exit(1);
      }

      // Toggle state in services-state.json only
      const state = await loadServicesState();
      const currentLive = state[serviceName]?.live ?? true;
      state[serviceName] = { live: !currentLive };
      const newState = state[serviceName].live ? "🟢 LIVE" : "🚧 MAINTENANCE";
      console.log(`Toggling ${serviceName} → ${newState}`);

      if (!dryRun) {
        await saveServicesState(state);
        // Reload services to pick up the new state
        Object.assign(services, await loadServices());
      }
      break;
    }

    case "add": {
      const serviceName = filteredArgs[1];
      const port = parseInt(filteredArgs[2], 10);

      if (!serviceName || !port) {
        console.error("Usage: bun generate.ts add <service> <port>");
        process.exit(1);
      }
      if (services[serviceName]) {
        console.error(`❌ Service '${serviceName}' already exists`);
        process.exit(1);
      }
      if (Object.values(services).some((s) => s.port === port)) {
        console.error(`❌ Port ${port} already in use`);
        process.exit(1);
      }

      // Add to structure file only (state defaults to live: true)
      const structure = await loadServicesStructure();
      structure[serviceName] = { port };
      console.log(`Adding ${serviceName} on port ${port}`);

      if (!dryRun) {
        await saveServicesStructure(structure);
      }
      break;
    }

    case "remove": {
      const serviceName = filteredArgs[1];
      if (!serviceName) {
        console.error("Usage: bun generate.ts remove <service>");
        process.exit(1);
      }
      if (!services[serviceName]) {
        console.error(`❌ Service '${serviceName}' not found`);
        process.exit(1);
      }

      // Remove from structure file
      const structure = await loadServicesStructure();
      delete structure[serviceName];
      console.log(`Removing ${serviceName}`);

      if (!dryRun) {
        await saveServicesStructure(structure);

        // Also clean up state file if it exists
        const state = await loadServicesState();
        if (state[serviceName]) {
          delete state[serviceName];
          await saveServicesState(state);
        }
      }
      break;
    }

    case undefined:
    case "generate": {
      // Default: just generate
      break;
    }

    default: {
      console.error(`Unknown command: ${command}`);
      console.error("Commands: list, maint, add, remove, generate (default)");
      process.exit(1);
    }
  }

  const caddyfile = generateCaddyfile(services);

  // Validate BEFORE the live file is touched — an invalid config must never
  // reach disk, even though a failed reload would leave Caddy itself running.
  if (!dryRun) {
    if ((await validateCaddyfile(caddyfile)) === "invalid") {
      console.error("\n❌ Aborting — no changes written. Fix services.json and retry.");
      process.exit(1);
    }
  }

  await writeCaddyfile(caddyfile, dryRun);

  if (!dryRun) {
    await reloadCaddy(dryRun);
  }
}

main();
